import type { Metadata } from "next";

import "./globals.css";
import Navbar from "@/components/Navigation/Navbar";
import { Footer } from "@/components/Footer";
import { Toaster } from "@/components/ui/toaster";
import { textPrimary, textSecondary } from "@/lib/fonts";
import StickyNavbar from "@/components/Navigation/StickyNavbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${textPrimary.variable} ${textSecondary.variable}`}
    >
      <head />

      <body className="bg-neutral-50">
        <StickyNavbar>
          <Navbar />
        </StickyNavbar>
        <main className="min-h-[75vh]  max-w-[3500px]">{children}</main>
        <Footer />

        <Toaster />
      </body>
    </html>
  );
}
